from torch.nn import Module
from torch import nn

#改模型
class onedimcnn(Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv1d(1, 64, 3, padding=1)
        self.bn1 = nn.BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True)
        #self.dropout = nn.Dropout(p=0.3)
        self.relu1 = nn.ReLU()
        self.pool1 = nn.MaxPool1d(4)
        self.conv2 = nn.Conv1d(64, 64, 3, padding=1)
        self.bn2 = nn.BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True)
        self.relu2 = nn.ReLU()
        self.pool2 = nn.MaxPool1d(4)
        self.conv3 = nn.Conv1d(64, 128, 3, padding=1)
        self.bn3 = nn.BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True)
        self.relu3 = nn.ReLU()
        self.pool3 = nn.MaxPool1d(4)
        self.conv4 = nn.Conv1d(128, 128, 3, padding=1)
        self.bn4 = nn.BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True)
        self.relu4 = nn.ReLU()
        self.pool4 = nn.MaxPool1d(5)

        self.fc1 = nn.Linear(6400, 640)
        self.dropout = nn.Dropout(p=0.5)
        # self.bn5 = nn.BatchNorm1d(num_features=640, eps=1e-05, momentum=0.1, affine=True)
        self.relu5 = nn.ReLU()
        self.fc2 = nn.Linear(640, 64)
        # self.dropout = nn.Dropout(p=0.5)
        # self.bn6 = nn.BatchNorm1d(num_features=64, eps=1e-05, momentum=0.1, affine=True)
        self.relu6 = nn.ReLU()
        self.fc3 = nn.Linear(64, 2)


    def forward(self, x):
        y = self.conv1(x)
        y = self.bn1(y)
        #y = self.dropout(y)
        y = self.relu1(y)
        y = self.pool1(y)
        y = self.conv2(y)
        y = self.bn2(y)
        #y = self.dropout(y)
        y = self.relu2(y)
        y = self.pool2(y)
        y = self.conv3(y)
        y = self.bn3(y)
        #y = self.dropout(y)
        y = self.relu3(y)
        y = self.pool3(y)
        y = self.conv4(y)
        y = self.bn4(y)
        #y = self.dropout(y)
        y = self.relu4(y)
        y = self.pool4(y)
        y = y.view(y.shape[0], -1)
        y = self.fc1(y)
        #y = self.bn5(y)
        y = self.dropout(y)
        y = self.relu5(y)
        y = self.fc2(y)
        #y = self.bn6(y)
        #y = self.dropout(y)
        y = self.relu6(y)
        y = self.fc3(y)
        return y

